accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from .views import home_views as home

from .views import chat_views as chat
from .views import groupchat_views as groupchat
from .views import like_comment_views as like_comment
from .views import notification_views as notification
from .views import post_views as post
from .views import user_views as user
from .views import groupchat_views as group_views

urlpatterns = [
    path("", home.HomeView, name="home_page"),
    path("notification/", home.notification, name="notification_page"),
    
#Authentication Urls
    path("register/",home.RegisterView, name="register_page"),
    path("login/",home.LoginView, name="login_page"),
    path("logout/",home.LogoutView, name="logout_page"),   
    
#Forgot Password
    path("password-reset/", auth_views.PasswordResetView.as_view(template_name="authentication/password_reset.html"), name="password_reset"),
    path("password-reset/done/", auth_views.PasswordResetDoneView.as_view(template_name="authentication/password_reset_done.html"), name="password_reset_done"),
    path("password-reset-confirm/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(template_name="authentication/password_reset_confirm.html"), name="password_reset_confirm"),
    path("password-reset-complete/", auth_views.PasswordResetCompleteView.as_view(template_name="authentication/password_reset_complete.html"), name="password_reset_complete"),
#Password Change
    path("password-change/", auth_views.PasswordChangeView.as_view(template_name="authentication/password_change.html"), name="password_change"),
    path("password-change/done/", auth_views.PasswordChangeDoneView.as_view(template_name="authentication/password_change_done.html"), name="password_change_done"),
    

#User Urls
    path('myprofile/', user.ProfileView, name='myprofile_page'),
    path("profileupdate/", user.ProfileUpdateView, name="profile_update_page"),
    path("profile/<str:username>/", user.SearchUserProfile, name="search_profile_page"),
    path('follow/<str:username>/', user.FollowUnfollowView, name='follow_unfollow'),
    path('followrequest/<str:username>/', user.send_follow_request, name='send_follow_request'),
    path('follow/request_accept/<int:req_id>/', user.follow_request_accept, name='follow_request_accept'), 
    path('follow/request_reject/<int:req_id>/', user.follow_request_reject, name='follow_request_reject'),
    path('follow_request_list/', user.follow_request_list, name='follow_request_list'),
    path('profile/<str:username>/followers/', user.FollowerListView, name='followers_list'),
    path('profile/<str:username>/following/', user.FollowingListView, name='following_list'),
    
    
    
# # #Post urls
    path("create_post/",post.CreatePostView, name="create_post_page"),
    path("hashtag/<str:hashtag>/", post.HashtagView, name="hashtag_posts"),
    path('post/<int:post_id>/', post.PostDetailView, name='post_detail'),
    path('post/<int:post_id>/edit/', post.EditPostView, name='edit_post'),
    path('post/<int:post_id>/delete/', post.DeletePostView, name='delete_post'),
    path('download/<int:media_id>/', post.download_post, name='download_post'),


# # #Like_Comment urls
    # path('post/<int:post_id>/like/', like_comment.LikePostView, name='like_post'),
    path('comment/<int:post_id>/', like_comment.AddCommentView, name='add_comment'),
    path("delete-comment/<int:comment_id>/", like_comment.DeleteCommentView, name="delete_comment"),
    path("edit-comment/<int:comment_id>/", like_comment.EditCommentView, name="edit_comment"),
    path("edit-reply/<int:reply_id>/", like_comment.EditReplyView, name="edit_reply"),
    path("delete-reply/<int:reply_id>/", like_comment.DeleteReplyView, name="delete_reply"),
    
    
# Chat Urls
    path("send_message/<str:username>/", chat.chat_view, name="send_message"),
    path("messages_lists/", chat.inbox_view, name="send_message"),
    # path("inbox/", chat.InboxView, name="inbox"),
    # path("conversation/<int:conversation_id>/", chat.ConversationView, name="view_conversation"),
    # path("delete_message/<int:message_id>/", chat.DeleteMessageView, name="delete_message"),
    
#Notification  Urls
    # path('notifications/', notification.NotificationsView, name='notifications_page'),
    # path('notifications/mark-as-read/', notification.NotificationReadView, name='mark_notifications_as_read'),
    path("search/", notification.SearchUserView, name="search_users"),

    # Group Related URLs
    path('groups/', group_views.groups_list, name='groups_list'),
    path('groups/create/', group_views.create_group, name='create_group'),
    path('groups/<int:group_id>/', group_views.group_detail, name='group_detail'),
    path('groups/<int:group_id>/join/', group_views.join_group, name='join_group'),
    path('groups/<int:group_id>/cancel_join/<int:user_id>/', group_views.cancel_join_request, name='cancel_join_request'),
    path('groups/<int:group_id>/leave/', group_views.leave_group, name='leave_group'),
    path('groups/<int:group_id>/add-member/', group_views.add_member, name='add_member'),
    path('groups/<int:group_id>/remove-member/<int:user_id>/', group_views.remove_member, name='remove_member'),
    path('groups/<int:group_id>/promote/<int:user_id>/', group_views.promote_member, name='promote_member'),
    path('groups/<int:group_id>/demote/<int:user_id>/', group_views.demote_member, name='demote_member'),
    path('groups/<int:group_id>/chats/', group_views.group_chat, name='group_chat'),
    path('groups/<int:group_id>/accept_request/<int:request_id>/', group_views.accept_join_request, name='accept_join_request'),
    path('groups/<int:group_id>/reject_request/<int:request_id>/', group_views.reject_join_request, name='reject_join_request'),
]



fotoflow/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

#all_urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),  
    path("accounts/", include("allauth.urls")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from .models_folder.chat_models import (
    Group,
    Message,
    GroupMember,
    GroupJoinRequest,
)
# -------------------------------------------

from .models_folder.notifications_models import (
    Notification,
)
# ----------------------------------------------

from .models_folder.post_models import (
    Post,
    PostMedia,
    Hashtag,
    Comment,
)
# --------------------------------------------

from .models_folder.user_models import (
    Profile,
    Follow,
)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models_folder.user_models import  Profile
from .models_folder.post_models import  Post, Comment

from .models_folder.chat_models import  Group

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email']

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.filter(username=username).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError("This username is already taken.")
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if not email:
            return email
        if User.objects.filter(email=email).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError("This email is already in use.")
        return email

    
    
class ProfileUpdateForm(forms.ModelForm):
    is_private = forms.BooleanField(
        required=False,
        label="Make my account private"
    )

    class Meta:
        model = Profile
        fields = ['profile_picture', 'bio', 'gender', 'is_private']


class PostForm(forms.ModelForm):
    media = forms.FileField(
        widget=forms.ClearableFileInput(), required=False
    )

    class Meta:
        model = Post
        fields = ["caption", "media"]
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        

class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        # exclude 'owner' and 'created_at' because they’ll be set in the view
        fields = ['name', 'description', 'is_private', 'image']
        
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter group name'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter description'}),
            'is_private': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'image': forms.FileInput(attrs={'class': 'form-control'}),
        }

accounts/views.py
from django.shortcuts import render, redirect
from .forms import GroupForm
from .models import GroupMember

def create_group(request):
    if request.method == 'POST':
        form = GroupForm(request.POST, request.FILES)
        if form.is_valid():
            group = form.save(commit=False)
            group.owner = request.user  # Step 1: make user the owner
            group.save()
            
            # Step 2: Add the user as an admin in GroupMember
            GroupMember.objects.create(
                group=group,
                user=request.user,
                role=GroupMember.ADMIN
            )

            return redirect('group_detail', group_id=group.id)  # or wherever you wanna go
    else:
        form = GroupForm()
    
    return render(request, 'your_template_name.html', {'form': form})

accounts/views/chat_views.py
from django.shortcuts import render, redirect, get_list_or_404, get_object_or_404
from django.http import HttpResponse,JsonResponse
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db.models import Count
from django.db.models import Max
from accounts.models_folder.user_models import  Profile, Follow
from accounts.models_folder.chat_models import  Message
from django.db.models import Q

@login_required(login_url='login_page')
def chat_view(request, username):
    other_user = get_object_or_404(User, username=username)
    room_name = get_roomname(other_user, request.user)
    print(f"Views(cv)-->RoomName: {room_name}")
    chats = Message.objects.filter(
        receiver__in = [other_user, request.user],
        sender__in = [other_user, request.user],
    ).exclude(deleted_for=request.user)
    chats = chats.order_by("timestamp")

    return render(request, 'chats/chat.html', {"chats": chats, "room_name": room_name, "other_user": other_user})

def get_roomname(user1, user2):
    usernames = sorted([user1.username, user2.username])
    print(f"Views(gr)-->RoomName: chat_{usernames[0]}_{usernames[1]}")
    return f"chat_{usernames[0]}_{usernames[1]}"
    
    
@login_required(login_url='login_page')
def inbox_view(request):
    group_ids = request.user.group_memberships.values_list('group', flat=True)
    chats = Message.objects.filter(Q(sender = request.user) | Q(receiver = request.user) | Q(group_id__in = group_ids))
    
    return render(request, 'chats/inbox.html', {"chats" : chats})
#     sender
# receiver
# group












# @login_required(login_url='login_page')
# def chat_view(request, username):
#     other_user = get_object_or_404(User, username=username)
#     room_name = get_roomname(other_user, request.user)
#     print(f"Views(cv)-->RoomName: {room_name}")
#     chats = Message.objects.filter(
#         receiver__in = [other_user, request.user],
#         sender__in = [other_user, request.user],
#     ).exclude(deleted_for=request.user)
#     chats = chats.order_by("timestamp")

#     return render(request, 'chats/chat.html', {"chats": chats, "room_name": room_name, "other_user": other_user})

# def get_roomname(user1, user2):
#     usernames = sorted([user1.username, user2.username])
#     print(f"Views(gr)-->RoomName: chat_{usernames[0]}_{usernames[1]}")
#     return f"chat_{usernames[0]}_{usernames[1]}"

accounts/views/like_comment_views.py
from django.shortcuts import render, redirect, get_list_or_404, get_object_or_404
from django.http import HttpResponse,JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from accounts.models_folder.post_models import  Post, PostMedia, Hashtag, Comment
from accounts.models_folder.notifications_models import  Notification


@login_required(login_url='login_page')
def LikePostView(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    user = request.user
    
    if user in post.likes.all():
        post.likes.remove(user)  # Unlike if already liked
    else:
        post.likes.add(user)  # Like the post
        
        # crating Notification for post owner
        if post.user != user:
            Notification.objects.create(
                sender=user,
                receiver=post.user,
                notification_type='like',
                post=post
            )

    return redirect(request.META.get('HTTP_REFERER', 'home_page'))

@login_required(login_url='login_page')
def AddCommentView(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    parent_id = request.POST.get("parent_id")  

    if request.method == "POST":
        text = request.POST.get("text")
        user = request.user
        if text:
            parent_comment = None
            if parent_id:
                parent_comment = Comment.objects.get(id=parent_id)  
            
            comment = Comment.objects.create(
                user=user,
                post=post,
                text=text,
                parent=parent_comment
            )

            #  Notification  comments on the post
            if parent_comment is None and post.user != user: 
                 
                Notification.objects.create(
                    sender=user,
                    receiver=post.user,
                    notification_type="comment",
                    post=post
                )

            # Notification for replies to a comment
            if parent_comment is not None and parent_comment.user != user:  
                Notification.objects.create(
                    sender=user,
                    receiver=parent_comment.user,
                    notification_type="reply",
                    comment=parent_comment
                )

            messages.success(request, "Comment added successfully!")

    return redirect("home_page")

@login_required(login_url='login_page')
def DeleteCommentView(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)

    # Check if the logged-in user is the owner of the comment
    if request.user == comment.user:
        comment.delete()
        messages.success(request, "Comment deleted successfully!")
    else:
        messages.error(request, "You are not allowed to delete this comment.")

    return redirect("home_page")  # Redirect to the homepage after deletion


@login_required(login_url='login_page')
def EditCommentView(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id, user=request.user)  # Ensure user owns comment

    if request.method == "POST":
        new_text = request.POST.get("text")
        if new_text:
            comment.text = new_text
            comment.save()
            messages.success(request, "Comment updated successfully!")
            return redirect("home_page")

    return render(request, "posts/edit_comment.html", {"comment": comment})

@login_required(login_url='login_page')
def EditReplyView(request, reply_id):
    reply = get_object_or_404(Comment, id=reply_id, user=request.user)  # Ensure user owns reply

    if request.method == "POST":
        new_text = request.POST.get("reply_text")
        if new_text:
            reply.text = new_text
            reply.save()
            messages.success(request, "Reply updated successfully!")
            return redirect("home_page")

    return render(request, "posts/edit_reply.html", {"reply": reply})


@login_required(login_url='login_page')
def DeleteReplyView(request, reply_id):
    reply = get_object_or_404(Comment, id=reply_id, user=request.user)  # Ensure user owns the reply

    if request.method == "POST":
        reply.delete()
        messages.success(request, "Reply deleted successfully!")
        return redirect("home_page")  # Redirect to the home page after deletion

    return render(request, "posts/delete_reply.html", {"reply": reply})

accounts/templates/group/add_member.html
<h2>Add Member to {{ group.name }}</h2>

<form method="post">
    {% csrf_token %}
    <input type="text" name="username" placeholder="Enter username to add">
    <button type="submit">Add</button>
</form>

<a href="{% url 'group_detail' group.id %}">Back</a>

accounts/templates/group/create_group.html
{% extends 'base.html' %}
{% load static %}
{% block css %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
<style>
    body {
        background-color: #f8f9fa;
    }
    .form-container {
        max-width: 600px;
        margin: 50px auto;
        padding: 30px;
        background-color: white;
        border-radius: 10px;
        box-shadow: 0 4px 12px rgba(0,0,0,0.1);
    }
    .form-title {
        text-align: center;
        margin-bottom: 30px;
    }
    .btn-primary {
        width: 100%;
    }
</style>
{% endblock %}
{% block content %}

<h2>Create a New Group</h2>

<div class="container">
    <div class="form-container">
        <h2 class="form-title">Create a New Group</h2>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            
            <div class="mb-3">
                <label for="id_name" class="form-label">Group Name</label>
                {{ form.name }}
            </div>

            <div class="mb-3">
                <label for="id_description" class="form-label">Description</label>
                {{ form.description }}
            </div>

            <div class="mb-3 form-check">
                {{ form.is_private }} 
                <label class="form-check-label" for="id_is_private">Make group private</label>
            </div>

            <div class="mb-3">
                <label for="id_image" class="form-label">Group Image</label>
                {{ form.image }}
            </div>

            <button type="submit" class="btn btn-primary">Create Group</button>
        </form>
    </div>
</div>

<a href="{% url 'groups_list' %}">Back to Groups</a>
{% endblock %}

{% block js %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
{% endblock %}

accounts/templates/group/group_chat.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{group.name}} Chat Room{% endblock %}
{% block css %}<link rel="stylesheet" href="{% static 'chat.css' %}">{% endblock %}
{% block oldblock %}
<h3>{{group.name}}: Group Chat</h3>
<a href="{% url "group_detail" group.id %}">group Detail</a>
<div id="chat-messages" style="border:1px solid #ccc; padding:10px; height:300px; overflow-y:scroll;">
    <!-- Previous Messages will come here via JS WebSocket -->
</div>

<!-- Send Message -->
<input type="text" id="message-input" placeholder="Type your message...">
<button onclick="sendmessage()">Send</button>
{% endblock %}


{% block content %}
<div class="chat-container">
    <div class="chat-header"><a href="{% url "group_detail" group.id %}">{{group.name}}</a></div>
    
    <!--Chat Message-->
    <div class="chat-box" id="chat-box">
        {% for chat in  chats%}
        <div class="message {% if chat.sender == request.user %}sent{% else %}received{% endif %}" 
             data-id="{{ chat.id }}" 
             ondblclick="likeMessage({{ chat.id }})">
        <strong>{{chat.sender.username}}</strong>:
        {% if chat.reply_to %}
        <div class="reply">↩️ Replying to: {{ chat.reply_to.text }}</div>

        {% endif %}
        {% if chat.is_deleted %}
        <p class="deleted-message">This message was deleted1</p>
        {% else %}
        <p id="msg-text-{{ chat.id }}">{{ chat.text }}</p>
        {% endif %}

        <small>{{ chat.timestamp|date:"H:i:s" }}</small>

        <span class="actions">
            <button class="delete-btn" onclick="confirmdelete({{chat.id}}, '{{chat.sender.username}}')">🗑</button>
            <button class="class" onclick="setReply({{chat.id}}, '{{chat.text}}')">↩️</button>
        </span>
        <span class="likes" id="likes--{{chat.id}}">
            ❤️ {{ chat.likes.count }}
        </span>
    </div>
        {% endfor %}
</div>

    <!-- Reply Preview -->
    <div id="reply-section" style="display: none;">
        Replying to: <span id="reply-text"></span>
        <button onclick="clearReply()">❌</button>
    </div>

    <div class="chat-input">
        <input type="hidden" id="reply-to">
        <input type="text" id="message-input" placeholder="Type a message.">
        <button onclick="sendmessage()">Send</button>
    </div>
{% endblock %}

{% block WebSocketJS %}
<script>
    const userId = "{{ request.user.id }}";
    const currentUser = "{{request.user.username}}";
    const groupId = "{{ group.id }}";

    const groupchatSocket = new WebSocket(
        `ws://${window.location.host}/ws/groupchat/${groupId}/`
    );

        groupchatSocket.onmessage = function(event) {
            const data = JSON.parse(event.data);
    
            if (data.action === "delete") {
                let msgDiv = document.querySelector(`.message[data-id='${data.message_id}']`);
                if (!msgDiv) return;
    
                if (data.delete_type === 'everyone') {
                    msgDiv.innerHTML = `<p class="deleted-message">This message was deleted.</p>`;
                } 
                else if (data.delete_type === 'me') {
                    msgDiv.style.display = 'none';  // 
                }
            }
            
            if (data.action === "like") {
                let likesSpan = document.getElementById(`likes-${data.message_id}`);
                if (likesSpan) {
                    likesSpan.innerHTML = `❤️ ${data.likes_count}`;
                }
                return;
            }
            addMessageToChat(data);
        }
    
    
        function addMessageToChat(data){
            console.log('sned ms')
            const chatBox = document.getElementById("chat-box")
            if (document.querySelector(`.message[data-id='${data.id}']`)){
                return;
            }
                let messageDiv = document.createElement("div");
                messageDiv.classList.add("message", data.sender === currentUser ? "sent" : "received");
                messageDiv.dataset.id = data.id;
                let content = `<strong>${data.sender}</strong>: `;
                if (data.reply_to) {
                    content += `<div class="reply"> to:   ${data.text}  <strong>↩️ Replying:</strong> ${data.reply_to}</div>`; 
                }
                content += `<p id="msg-text-${data.id}">${data.text || ""}</p>`; 
                content += `<small>${new Date().toLocaleTimeString()}</small>`;
                content += `
                <span class="actions">
                    <button class="delete-btn" onclick="confirmdelete(${data.id}, '${data.sender}')">🗑</button>
                    <button class="reply-btn" onclick="setReply(${data.id})">↩️</button>
                </span>
            <span class="likes" id="likes-${data.id}">❤️ ${data.likes || 0}</span>
        
            `;
        
            messageDiv.innerHTML = content;
            messageDiv.ondblclick = () => likeMessage(data.id);
    
                chatBox.appendChild(messageDiv);
               // chatBox.appendChild(messageDiv);
                chatBox.scrollTop = chatBox.scrollHeight;
        }
    
    // Text&Reply
        function sendmessage(){
            const messageInput = document.getElementById("message-input");
            const replyTo = document.getElementById("reply-to").value || null;
            let message = messageInput.value.trim();
            console.log(replyTo)
            if (message || replyTo){
            groupchatSocket.send(JSON.stringify({text: message, reply_to: replyTo}));
            messageInput.value = "";
            document.getElementById("reply-to").value = "";
            }
    
        }
        function setReply(messageId, messageText){
            document.getElementById("reply-to").value = messageId;
            document.getElementById("reply-text").innerText = messageText;
            document.getElementById("reply-section").style.display = "block";
            document.getElementById("message-input").focus();
        }
        function clearReply(){
            document.getElementById("reply-to").value = "";
            document.getElementById("reply-section").style.display = "none";
        }        
    //////////////////////////
        function confirmdelete(messageId, sender) {
            let modal = document.createElement("div");
            modal.classList.add("delete-modal");
            let modalContent = `
                <div class="modal-content"> 
                    <p>Are you sure you want to delete this message?</p>
                    ${sender === currentUser ? 
                    `<button onclick="deleteMessage('${messageId}', 'everyone')">Delete for everyone</button>` : ""}
                    <button onclick="deleteMessage('${messageId}', 'me')">Delete for me</button>
                    <button onclick="closeModal()">Cancel</button>
                </div>
            `;
            modal.innerHTML = modalContent;
            document.body.appendChild(modal);
        }
        function deleteMessage(messageId, type) {
            groupchatSocket.send(JSON.stringify({ action: "delete", message_id: messageId, delete_type: type }));
            closeModal();
        }
        function closeModal() {
            document.querySelector(".delete-modal").remove();
        }
    /////////////////////////////////////////////////////////////////////
    
        function likeMessage(messageId) {
            groupchatSocket.send(JSON.stringify({ action: "like", message_id: messageId }));
        }
    
        document.addEventListener("DOMContentLoaded", function () {
            const chatBox = document.getElementById("chat-box");
            chatBox.scrollTop = chatBox.scrollHeight;
        });
    </script>
{% endblock %}

accounts/templates/group/group_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h2>Group: {{ group.name }} 
    {% if is_admin %}
        <a href="{% url 'add_member' group.id %}">Add Members</a>
    {% endif %}
</h2>


<!-- Group Profile Picture -->
{% if group.image %}
    <img src="{{ group.image.url }}" alt="Group Image" width="100" height="100">
{% else %}
    <img src="{% static 'default_group.png' %}" alt="Default Group Image" width="100" height="100">
{% endif %}

<!-- Group Details -->
<p>Description: {{ group.description|default:"No Description" }}</p>
<p>Owner: {{ group.owner.username }}</p>
<p>Private: {{ group.is_private }}</p>

<hr>

<h3>Group Members:</h3>
<ul>
    {% for member in members %}
        <li>{{ member.user.username }} - {{ member.role }}: 
        {% if is_admin %}
            {% if member.user != request.user %}
                <a href="{% url 'remove_member' group.id member.user.id %}">Remove</a>
            {% endif %}
            {% if member.role == 'member' %}
            <a href="{% url 'promote_member' group.id member.user.id %}">Promote to Admin</a>
            {% endif %}
            {% if member.role == 'admin' %}
            <a href="{% url 'demote_member' group.id member.user.id %}">Demote to Member</a>
            {% endif %}
        {% endif %}

        </li>
    {% empty %}
        <li>No members in this group.</li>
    {% endfor %}
</ul>
{% if is_admin  %}
<h3>Pending Join Requests:</h3>
    <ul>
        {% for req in join_requests %}
            <li>
                {{ req.user.username }} 
                
                <form action="{% url 'accept_join_request' group.id req.id %}" method="post" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit">Accept</button>
                </form>

                <form action="{% url 'reject_join_request' group.id req.id %}" method="post" style="display:inline;">
                    {% csrf_token %}
                    <button type="submit">Reject</button>
                </form>
            </li>
        {% endfor %}
    </ul>
{% endif %}
<hr>

<!-- Leave Group Option -->
<form method="post" action="{% url 'leave_group' group.id %}">
    {% csrf_token %}
    <button type="submit">Leave Group</button>
</form>

<hr>
<a href="{% url "group_chat" group.id %}">Bacck To group Chat</a>

{% endblock %}